### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by fivehills** [LanguageMachines/timbl#10]
Hi,
After installing ticcutils successfully, I met some problems in installing timbl.
It seems that I have installed all dependencies listed; however, after implementing "make", I have got some errors like the following: 
 make[2]: Entering directory '/home/kun/Software/entropy/timbl-6.4.12/demos'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/kun/Software/entropy/timbl-6.4.12/demos'
Making all in docs
make[2]: Entering directory '/home/kun/Software/entropy/timbl-6.4.12/docs'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/kun/Software/entropy/timbl-6.4.12/docs'
Making all in m4
make[2]: Entering directory '/home/kun/Software/entropy/timbl-6.4.12/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/kun/Software/entropy/timbl-6.4.12/m4'
make[2]: Entering directory '/home/kun/Software/entropy/timbl-6.4.12'
make[2]: Leaving directory '/home/kun/Software/entropy/timbl-6.4.12'
make[1]: Leaving directory '/home/kun/Software/entropy/timbl-6.4.12'
% make install
Making install in src
make[1]: Entering directory '/home/kun/Software/entropy/timbl-6.4.12/src'
make[2]: Entering directory '/home/kun/Software/entropy/timbl-6.4.12/src'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libtimbl.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libtimbl.so.4.0.1 /usr/local/lib/libtimbl.so.4.0.1
/usr/bin/install: cannot remove '/usr/local/lib/libtimbl.so.4.0.1': Permission denied
Makefile:584: recipe for target 'install-libLTLIBRARIES' failed
make[2]: *** [install-libLTLIBRARIES] Error 1
make[2]: Leaving directory '/home/kun/Software/entropy/timbl-6.4.12/src'
Makefile:1006: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/kun/Software/entropy/timbl-6.4.12/src'
Makefile:465: recipe for target 'install-recursive' failed

Who would like to help me solve the problem.

**Comment by proycon** [comment]
This just seems like you ran ``make install`` without ``sudo`` is that right?

I'd recommend using our [LaMachine](https://github.io/LaMachine) distribution, which does all compilation for you, if you find manual compilation too complicated.

**Comment by kosloot** [comment]
Indeed, LaMachine might be the simplest choice.

Otherwise:
For `make install` you need sudo rights.
I assume you used `sudo make install` for ticcutils?  Because otherwise that should gave failed already.
If you don't have sudo rights you can always use configure with the `--prefix` option.
Just let it point to a directory that you have write access to, like `/home/kun/Software/local`
Make sure to use the same prefix for all of our software.

**Comment by kosloot** [comment]
closing after 4 years of no  response
