### ISSUE TITLE
Update debian package for timbl v6.4.13

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/timbl#5]
Note: Has SO version bump!

**Comment by proycon** [comment]
@kosloot Same question as for libfolia before: we had a libtimbl4 and SO version bumped to 4.0.1, a libtimbl5 with SO bump to 5 might make most sense?

**Comment by kosloot** [comment]
Well, I don't recall any API or ABI break. So bumping might not be necessary.
But recall might not be enough :)

Testing these dependencies is rather difficult.
- does Timbl work out of the box with the newer ticcutils
- OR does it need relinking
- OR does it need recompiling

And then:
- does stuff build upon Timbl need relinking or recompiling

I don't have a good idea about what the best solution would be.
Just rebuilding everything (like LaMachine) is the 'easy' variant

**Comment by proycon** [comment]
Ok, the library bump seemed to happen in: https://github.com/LanguageMachines/timbl/commit/c0df5e3868068e4b713ea20aa10f356a79c9a2c6  , which only does some removals, so I suppose that should be safe.

Yeah, I don't have an exact sight on this ABI breakage stuff either, it's complex. Ideally, we should do symbol tracking as described in https://www.debian.org/doc/manuals/maint-guide/advanced.en.html#librarysymbols 

Another good resource is: https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B

**Comment by kosloot** [comment]
yes, I read the second document (several times) and the bottom-line is, that it is very difficult :)
especially in a research environment as ours.

**Comment by proycon** [comment]
Ready on alioth

**Comment by proycon** [comment]
ready on alioth again

**Comment by proycon** [comment]
Ready on [salsa](https://salsa.debian.org/science-team/timbl)
