### ISSUE TITLE
Timbl Installation Error

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/timbl#7]
Hi!

I'm trying to install frog on ubuntu 16.04, which requires timbl. When I'm installing timbl, I run into a problem. Configuration works fine, but during compilation:
```
/usr/local/lib/libticcutils.so: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
/usr/local/lib/libticcutils.so: undefined reference to `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
collect2: error: ld returned 1 exit status
Makefile:684: recipe for target 'timbl' failed
make[2]: *** [timbl] Error 1
make[2]: Leaving directory '/mnt/b5320167-5dbd-4498-bf34-173ac5338c8d/Tools/timbl-6.4.10/src'
Makefile:465: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/mnt/b5320167-5dbd-4498-bf34-173ac5338c8d/Tools/timbl-6.4.10'
Makefile:374: recipe for target 'all' failed
make: *** [all] Error 2
```
I'm attaching the full report as "log".

I've used the latest ticcutils-0.17 release, and I'm trying to install frog-0.13.9. Timbl version that is failing is timbl-6.4.10.

Thanks for any suggestions about what might be causing this problem!

Simon Suster

@SimonSuster :  ADDED as a GitHub issue.

**Comment by kosloot** [comment]
Hello @simonsuster

first of all, you might be better of by using LaMachine, (
https://github.com/proycon/LaMachine )
which should help to avoid all kind of dependency issues.

If that is not an option, lets try to find out what is wrong:

1. Did ticcutils really got installed correctly?
   - no complaints about missing boost?
     (Question: how did you install libboost?)
   - please try 'make check' in the ticcutils dir too.
2. to be sure, run 'ldconfig /usr/local/lib' after 'make install'
3. try making timbl again

Let me know if this helps or raises issues again.

Ko vd Sloot
Timbl Development.

**Comment by SimonSuster** [comment]
Thanks, Ko, switching to LaMachine by using vagrant worked for me OK!

Still, to get back to your questions regarding the local install:
> Did ticcutils really got installed correctly?

It appeared so as there were no errors during make and make install. But make check indeed resulted in the error that I reported.

> no complaints about missing boost?

There were no complaints. I had  libboost-all-dev 1.58.0.1ubuntu1 already installed (that is the latest version for ubuntu 16.04.

**Comment by kosloot** [comment]
Hmm,
and did you try ldconfig? as root? 
With the installdir of boost as parameter too.

Otherwise I am out of ideas for the moment.

**Comment by kosloot** [comment]
Closing due to lack of feedback
