### ISSUE TITLE
add a parameter to select the N best features

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/timbl#8]
For some tasks, with a lot of features, it might be handy to let Timbl select the top N features, based on the current weight, and use only those to build the tree. Also an implicit -mI for all the other features.

e.g a --cutoff 1000, would select the 1000 'best ranked' features. Assuming more than 1000 are available :)

comment welcome....

**Comment by antalvdb** [comment]
No comments, other than that it's a good idea.

**Comment by kosloot** [comment]
small note: The Feature weights are at first calculated using ALL available features.
After choosing the N best, the weights have to be recalculated for only those N.
Otherwise surprises might happen.
for instance: when restoring an IB1 tree from a file, Timbl calculates the weights based on the info in the file. (Also NOT taking into account the ignored features.)
These weights should match those of an tree prior to storing.

So the scheme is:
- calculate the weights
- select the N best
- recalculate the weights, with a -mI:k for all all NOT in the N best.

**Comment by kosloot** [comment]
A '--limit' option is implemented now.
simple tests did succeed, but more thorough tests are welcome.

**Comment by kosloot** [comment]
No feedback yet. I assume this is working.
